#! /usr/bin/python

import sys
import os
import subprocess
rootDir = sys.argv[1]
projName = sys.argv[2]
os.chdir(rootDir)
if not os.path.exists(os.path.join(projName, "src", "main", "scala")):
    os.makedirs(os.path.join(projName, "src", "main", "scala"))
if not os.path.exists(os.path.join(projName, "src", "main", "resources")):
    os.makedirs(os.path.join(projName, "src", "main", "resources"))
if not os.path.exists(os.path.join(projName, "src", "test", "scala")):
    os.makedirs(os.path.join(projName, "src", "test", "scala"))
if not os.path.exists(os.path.join(projName, "src", "test", "resources")):
    os.makedirs(os.path.join(projName, "src", "test", "resources"))
if not os.path.exists(os.path.join(projName, "project")):
    os.makedirs(os.path.join(projName, "project"))
os.chdir(projName)
f = open("build.sbt", 'w')
f.write("name := \""+projName+"\"\n\n")
f.write("version := \"1.0\"\n\n")
f.write("scalaVersion := \"2.9.3\"\n\n")

f.write("libraryDependencies += \"org.spark-project\" %% \"spark-core\" % \"0.7.3\"\n\n")
f.write("resolvers ++= Seq("+
        "\"Akka Repository\" at \"http://repo.akka.io/releases/\","+
        "\"Spray Repository\" at \"http://repo.spray.cc/\")\n\n")
